### ISSUE TITLE
'suny_ani', 'clod_ani', etc -  was not declared in this scope

### ISSUE THREAD

**Issue by zounder1** [gquiring/MorphingClockQ#1]
Hi.  First off.  Thank you for keeping the MorphingClock updated!  It is much appreciated.

I am trying to compile the program and get the following error attached below.  I'm wondering if I am missing some library or includes that should declare these items?

I see the missing items seem to be in "TinyIcons.h"

Note that I need to use PxMatrix version 1.8.2 for my panel.  Arduino offers 1.8.1 so I downloaded it from the github repository.

I can work my way through some code, but I am not an expert!  So please feel free to ask me any questions for more information.

-------------------------------
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new can abort), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\***\OneDrive - *****\Documents\Arduino\Projects\MorphingClockQ\MorphingClockQ.ino: In function 'void draw_animations(int)':

MorphingClockQ:1158:9: error: 'suny_ani' was not declared in this scope
    af = suny_ani[stp%5];
         ^

MorphingClockQ:1161:9: error: 'clod_ani' was not declared in this scope
    af = clod_ani[stp%10];
         ^

MorphingClockQ:1164:9: error: 'ovct_ani' was not declared in this scope
    af = ovct_ani[stp%5];
         ^

MorphingClockQ:1167:9: error: 'rain_ani' was not declared in this scope
    af = rain_ani[stp%5];
         ^

MorphingClockQ:1170:9: error: 'thun_ani' was not declared in this scope
    af = thun_ani[stp%5];
         ^

MorphingClockQ:1173:9: error: 'snow_ani' was not declared in this scope
    af = snow_ani[stp%5];
         ^

MorphingClockQ:1176:9: error: 'mist_ani' was not declared in this scope
    af = mist_ani[stp%4];
         ^

MorphingClockQ:1179:9: error: 'mony_ani' was not declared in this scope
    af = mony_ani[stp%17];
         ^

MorphingClockQ:1182:9: error: 'mistn_ani' was not declared in this scope
    af = mistn_ani[stp%4];
         ^

MorphingClockQ:1185:9: error: 'clodn_ani' was not declared in this scope
    af = clodn_ani[stp%10];
         ^

MorphingClockQ:1188:9: error: 'ovctn_ani' was not declared in this scope
    af = ovctn_ani[stp%1];
         ^

exit status 1

'suny_ani' was not declared in this scope

**Comment by gquiring** [comment]
That's odd.  Do you have TinyIcons.h in the same directory as the .ino?
Were there any other errors that it could not find the include file?

**Comment by zounder1** [comment]
Yeah.  It is weird.  I have the TinyIcons.h file in the same directory as the .ino

I'm stumped for now.  I'm won't be able to look at this for a few days most odds.  I plan on spinning up a new VM and install a fresh copy of the Arduino IDE to see if I get the same problem.

**Comment by gquiring** [comment]
I know you mentioned you need the other version for your RGB board but
could try the versions I used just to see if it compiles clean.

**Comment by gquiring** [comment]
I figured out your issue, you let the IDE move the source to MorphingClockQ
but it did move anything else.

**Comment by gquiring** [comment]
Skip that last message, I downloaded the Zip from Github on my 2nd computer
and tried to compile it and got the same error you had.  I missed a file
when uploading to Guthub.  WeatherIcons.h is what you need to resolve the
issue (it's on Github now).  Sorry for the oops!

**Comment by zounder1** [comment]
YES!  The program is compiling properly now!  I'm glad I reported the issue - that way the bug could be squashed and not impact anyone else in the future.

BTW, it compiled fine with pxmatrix 1.8.2 from Github.

**Comment by zounder1** [comment]
Thank you for your help fixing this!  Closing this issue as it is resolved.
